import createFetchClient, { type ClientOptions, type Client } from "openapi-fetch";
import type { paths } from "../gen/unsplash.d.ts"; // generated by openapi-typescript
export type { paths } from "../gen/unsplash.d.ts"; // generated by openapi-typescript
export type * from "openapi-fetch";
export { trackNonHotLinkedPhotoView } from "./beacon.ts";

const DEFAULT_BASE_URL = "https://api.unsplash.com/";
const API_VERSION = "v1";

type Config = {
  accessKey?: string;
  apiVersion?: string;
} & ClientOptions;

export type UnsplashApi = Client<paths, `${string}/${string}`>;

/**
 * Creates an {@link https://openapi-ts.dev/openapi-fetch/|openapi-fetch} client for the unsplash api.
 *
 * @see {@link https://unsplash.com/documentation|Unsplash's documentation} for endpoints details.
 * @see {@link https://openapi-ts.dev/openapi-fetch/|openapi-fetch's documentation} for advanced usage.
 *
 * @example
 * ```
 * // Simple initialization
 * import { createClient } from "unsplash-js";
 * const client = createApi({
 *   accessKey: process.env.UNSPLASH_ACCESS_KEY
 * });
 *
 * await client.GET("/photos/{assetSlug}", {
 *   params: {
 *     path: { assetSlug: "GuRkV6x5L8L" }
 *   }
 * })
 * ```
 */
export const createApi = ({
  accessKey,
  apiVersion = API_VERSION,
  headers,
  baseUrl = DEFAULT_BASE_URL,
  ...config
}: Config = {}): UnsplashApi => {
  const client = createFetchClient<paths>({
    ...config,
    querySerializer: {
      // Handles the few array query parameters that should
      // be passed as a comma-separated list.
      array: { style: "form", explode: false },
      ...config.querySerializer,
    },
    baseUrl,
    headers: {
      ...headers,
      "Accept-Version": apiVersion,
      ...(accessKey !== undefined ? { Authorization: `Client-ID ${accessKey}` } : {}),
    },
  });

  return client;
};
