import createFetchClient, { ClientOptions } from "openapi-fetch";
import type { paths } from "../gen/unsplash"; // generated by openapi-typescript

const DEFAULT_BASE_URL = "https://api.unsplash.com/";
const API_VERSION = "v1";

type Config = {
  accessKey?: string;
  apiVersion?: string;
} & ClientOptions;

export const createApi = ({
  accessKey,
  apiVersion = API_VERSION,
  headers,
  baseUrl = DEFAULT_BASE_URL,
}: Config) => {
  const client = createFetchClient<paths>({
    baseUrl,
    headers: {
      ...headers,
      "Accept-Version": apiVersion,
      ...(accessKey !== undefined ? { Authorization: `Client-ID ${accessKey}` } : {}),
    },
  });

  return client;
};
