name: CI
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
jobs:
  build:
    name: Build, lint, format and test

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Use Node "24.x"
        uses: actions/setup-node@v6
        with:
          node-version: "24.x"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Format
        run: pnpm format --check

      - name: Lint
        run: pnpm lint

      - name: Generate openapi types
        run: pnpm gen:type

      - name: Build
        run: pnpm build

      - name: Test
        run: pnpm test

      - name: Check size
        if: ${{ github.event_name == 'pull_request' && github.base_ref == 'master'}}
        uses: andresz1/size-limit-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
