name: Publish

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Use Node "24.x"
        uses: actions/setup-node@v4
        with:
          node-version: "24.x"
          cache: "pnpm"

      - name: Install
        run: pnpm install --frozen-lockfile

      - name: Generate openapi types
        run: pnpm gen:type

      - name: Build
        run: pnpm build

      - name: Publish
        run: pnpm stage publish --provenance --tag "$(jq --raw-output '.version | match("alpha|beta").string // "latest"' < package.json)"
